### ISSUE TITLE
Re-write README.md

### ISSUE THREAD

**Issue by ncdulo** [ncdulo/suppylement#9]
The first thing visitors to this repository will see on GitHub is going to be the `README.md` file. This is paramount to explaining the project, it's goals and basic use instructions.

As we continue to develop, I feel we may be losing some initial interest from visitors by keeping up the original bare-bones `README.md`. The current version was never intended to be used long term and it's time we prioritize re-writing to reflect the current state of PyMaengDa.

Items to be included may include, but are not limited to:
 - [x] General overview (PR #16)
 - [x] Current development status (PR #16)
 - [ ] Development goals/roadmap
 - [x] Requirements (PR #11)
 - [x] Basic installation instructions (venv, pip install, run-in-place, etc) (PR #11, Fix in PR #16)
 - [x] Basic use instructions with reference to main documentation when available (PR #16)
 - [ ] Contributing basics with link to `CONTRIBUTING.md`

**Comment by ncdulo** [comment]
This issue is currently being worked on in PR #11
